## This config was generated by cloudtool from /kickstart/_tpl/etc/*

<?php

$kickApacheVhostConfig = getenv("KICK_APACHE_VHOST_CONFIG");


?>
<Directory /var/www/html>
    AllowOverride All
    DirectoryIndex index.php index.html
</Directory>

<VirtualHost *>
    ServerAdmin webmaster@localhost
    DocumentRoot /var/www/html
    CustomLog /dev/null combined

    ## Custom configuration from .kick.yml "apache_vhost_config":

    <?php
    if( ! empty($kickApacheVhostConfig))
        echo $kickApacheVhostConfig;
    ?>

</VirtualHost>



