## From: github.com/nfra-project/nfra-skel
##
## Build on push to braches
##
## Examples
## Branch: release/1.1   -> ghcr.io/some/repo:1.1

name: build_and_push_to_github

## SECURITY: Do not youe "pull_request_target" nr "pull_request" here! See
## https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
on:
  schedule:
    - cron: '37 22 * * *'  # on Wednesday at 6:22
  push:
    branches:
      - main
      - master
      - "release/[0-9]+.[0-9]+"
    tags:
      - "release/[0-9]+.[0-9]+.[0-9]+"

jobs:
  build_and_push_github:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v2
        with:
          ref: release/8.0     # Modify this to your branch for releases
      - name: Build
        run: |
          docker build --pull --no-cache -t test/image .

      - name: Test
        run: |
          cd test/
          ./../.kicker/kickstart.static.sh --offline :test
          cd ..

      - name: Push
        run: |
          CI_BUILD_NAME=$GITHUB_REF
          [[ "$GITHUB_REF" == "refs/heads/master" ]] && CI_BUILD_NAME=unstable
          [[ "$GITHUB_REF" == "refs/heads/main" ]] && CI_BUILD_NAME=unstable
          CI_BUILD_NAME=${CI_BUILD_NAME#refs/heads/release/}
          CI_BUILD_NAME=${CI_BUILD_NAME#refs/tags/release/}
          CI_REGISTRY_IMAGE=$CI_REGISTRY/$GITHUB_REPOSITORY:$CI_BUILD_NAME
          docker tag test/image $CI_REGISTRY_IMAGE
          echo "$CI_REGISTRY_PASSWORD" | docker login --username $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
          docker push $CI_REGISTRY_IMAGE
        env:
          CI_REGISTRY: ghcr.io
          CI_REGISTRY_USER: giblab-user
          CI_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}