## From: github.com/nfra-project/nfra-skel
##
## Build on push to braches
##
## Examples
## Branch: release/1.1   -> ghcr.io/some/repo:1.1

name: schedule-unstable

## SECURITY: Do not youe "pull_request_target" nr "pull_request" here! See
## https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
on:
  schedule:
    - cron: '15 10 * * 1,3' # on Monday and Thursday

jobs:
  build_and_push_github:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine CI Branch and Image Name
        run: |
          CI_BRANCH=$(git tag)
          echo "CI_BRANCH 1: $CI_BRANCH"
          [[ "$CI_BRANCH" == "" ]] && CI_BRANCH=$(git branch --show-current)
          echo "CI_BRANCH 2: $CI_BRANCH"
          [[ "$CI_BRANCH" == "master" ]] && CI_BRANCH=unstable
          echo "CI_BRANCH 3: $CI_BRANCH"
          [[ "$CI_BRANCH" == "main" ]] && CI_BRANCH=unstable
          echo "CI_BRANCH 2: $CI_BRANCH"
          CI_BUILD_NAME=${CI_BRANCH#release/}
          CI_BUILD_NAME=${CI_BUILD_NAME#refs/tags/release/}
          CI_REGISTRY_IMAGE=ghcr.io$CI_REGISTRY/$GITHUB_REPOSITORY:$CI_BUILD_NAME
          echo "Final image name: $CI_REGISTRY_IMAGE"
          echo "CI_REGISTRY_IMAGE=$CI_REGISTRY_IMAGE" >> $GITHUB_ENV

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.CI_REGISTRY_IMAGE }}
          platforms: linux/amd64,linux/arm64



